version: '3.7'

services:

  hneil-prod:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production