version: '3.7'

services:

  local:
    container_name: app-local
    build:
      context: ./app
      dockerfile: Dockerfile.local
    ports:
      - '8080:3000'
    volumes:
      - /app/node_modules