version: '3.7'

services:

  app:
    container_name: hneil-app
    build:
      context: ./app
      dockerfile: Dockerfile.local
    ports:
      - '8080:3000'
    volumes:
      - .:/src
      - /node_modules
    environment:
      - NODE_ENV=development