version: '3.7'

services:

  app:
    container_name: hneil-app
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production