# base image
FROM node:13.2.0-alpine
RUN apk update && \
    apk add sudo

# set working directory
WORKDIR /app
COPY . /app

# RUN sudo npm install -g --unsafe-perm node-sass
RUN npm i --silent

CMD [ "npm", "start" ]